/// forms.dart is soley for the formations.

Map glider() {
  return {
    '1x1': false,
    '1x2': false,
    '1x3': false,
    '1x4': false,
    '1x5': false,
    '2x1': false,
    '2x2': false,
    '2x3': true,
    '2x4': false,
    '2x5': false,
    '3x1': false,
    '3x2': false,
    '3x3': false,
    '3x4': true,
    '3x5': false,
    '4x1': false,
    '4x2': true,
    '4x3': true,
    '4x4': true,
    '4x5': false,
    '5x1': false,
    '5x2': false,
    '5x3': false,
    '5x4': false,
    '5x5': false,
  };
}

Map rPentomino() {
  return {
    '1x1': false,
    '1x2': false,
    '1x3': false,
    '1x4': false,
    '1x5': false,
    '2x1': false,
    '2x2': false,
    '2x3': true,
    '2x4': true,
    '2x5': false,
    '3x1': false,
    '3x2': true,
    '3x3': true,
    '3x4': false,
    '3x5': false,
    '4x1': false,
    '4x2': false,
    '4x3': true,
    '4x4': false,
    '4x5': false,
    '5x1': false,
    '5x2': false,
    '5x3': false,
    '5x4': false,
    '5x5': false,
  };
}
